name: Test Cron

on:
  schedule:
    - cron: '* * * * *'  # Запуск каждую минуту
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run a test command
        run: echo "Cron job executed!"
